### ISSUE TITLE
Crash when kill app and start again

### ISSUE THREAD

**Issue by dcortes22** [Adobe-Marketing-Cloud/video-heartbeat-v2#12] opened 2018-02-05 23:59 UTC
Hello I'm using the video-heartbeat-v2 sdk for iOS, we have a very strange crash, when we kill the app and start again. After 3 times we received a crash with the current stack trace:

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-update watchdog transgression: exhausted real (wall clock) time allowance of 10.00 seconds |  | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-update | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 7.220 (user 7.220, system 0.000), 36% CPU", | "Elapsed application CPU time (seconds): 0.060, 0% CPU" | )
Triggered by Thread:  0

Filtered syslog:
None found

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x0000000186234138 __psynch_mutexwait + 8
1   libsystem_pthread.dylib       	0x000000018634b660 _pthread_mutex_lock_wait + 96
2   libsystem_pthread.dylib       	0x000000018634b5a4 _pthread_mutex_lock_slow$VARIANT$mp + 264
3   libobjc.A.dylib               	0x00000001859749e8 recursive_mutex_tt<false>::lock+ 84456 () + 16
4   libobjc.A.dylib               	0x0000000185978248 objc_sync_enter + 28
5   AmpAdobeHeartbeat             	0x000000010651fbf4 -[ADB_HB_PluginManager triggerEvent:] + 84
6   AmpAdobeHeartbeat             	0x0000000106502894 -[ADB_HB_BasePlugin _trigger:info:] + 288
7   AmpAdobeHeartbeat             	0x00000001064f75cc -[ADB_HB_ClockService onTick:interval:tick:] + 308
8   AmpAdobeHeartbeat             	0x00000001064ef0d0 -[ADB_HB_TimerManager _onTick] + 804
9   Foundation                    	0x000000018711c5b8 __NSFireTimer + 88
10  CoreFoundation                	0x00000001866c7dc0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
11  CoreFoundation                	0x00000001866c7ae4 __CFRunLoopDoTimer + 864
12  CoreFoundation                	0x00000001866c72e4 __CFRunLoopDoTimers + 248
13  CoreFoundation                	0x00000001866c4ecc __CFRunLoopRun + 1928
14  CoreFoundation                	0x00000001865e4c58 CFRunLoopRunSpecific + 436
15  GraphicsServices              	0x0000000188490f84 GSEventRunModal + 100
16  UIKit                         	0x000000018fd3d5c4 UIApplicationMain + 236
17  News                       	0x0000000103536a44 0x102ac4000 + 10955332
18  libdyld.dylib                 	0x000000018610456c start + 4`

It seems the [ADB_HB_TimerManager _onTick] is blocking the UI Thread on start.

Can anybody help me?

**Comment by praveek** [comment] 2018-02-16 19:10
Hi @dcortes22 ,

We have released a new version of our library on iOS (https://github.com/Adobe-Marketing-Cloud/video-heartbeat-v2/releases/tag/ios-v2.1.0).

Can you verify if you still see the issue ? 

Thanks,
Praveen

**Comment by himanshuphalak** [comment] 2018-03-06 18:33
@dcortes22 any updates on this? Please let us know if latest SDK version fixes the issue for you.

**Comment by dcortes22** [comment] 2018-03-13 19:07
Hey @himanshuphalak the crash now happens less, but sometimes we still have troubles this is the stack trace:

![heartbeatsdeadlockpt2](https://user-images.githubusercontent.com/1170942/37364210-825a97de-26bf-11e8-9b4b-6897df486eae.png)

**Comment by himanshuphalak** [comment] 2018-03-16 15:33
Hey @dcortes22, sorry to hear you are still seeing some issues. Can you open a ticket with [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html) and provide additional details on this with logs and maybe steps to reproduce if you have? We can take a look into it once we have additional details.

**Comment by himanshuphalak** [comment] 2018-05-03 20:17
Closing this issue since we are tracking this item through client care.

**Closed by himanshuphalak** 2018-05-03 20:17 UTC
